GET http://localhost:5052/

###
GET http://localhost:5052/libraryitems?sort=category

###
GET http://localhost:5052/libraryitems/

### //public record LibraryItemInput(int CategoryId, string? Title, string Type, string? Author, int? Pages, int? RunTimeMinutes, string? Borrower, DateTime? BorrowDate);
POST http://localhost:5052/libraryitems
content-type: application/json

{
    "categoryId": 1,
    "title": "To Be Deleted",
    "type": "referencebook",
    "author": "Herr. Test",
    "pages": 900,
    "runTimeMinutes": null
}

###
PUT http://localhost:5052/libraryitems/3
content-type: application/json

{
    "categoryId": 7,
    "title": "Tale of the Ring 3",
    "type": "book",
    "author": "Mr. Tolk",
    "pages": 345,
    "runTimeMinutes": null
}

###
POST http://localhost:5052/libraryitems/5/borrow
content-type: application/json

{
    "name": "David"
}

###
POST http://localhost:5052/libraryitems/5/return

###
DELETE http://localhost:5052/libraryitems/8

###
GET http://localhost:5052/categories

###
GET http://localhost:5052/categories/1

###
POST http://localhost:5052/categories
content-type: application/json

{
    "name": "Action"
}

###
PUT http://localhost:5052/categories/2
content-type: application/json

{
    "name": "Mystery+"
}

###
DELETE http://localhost:5052/categories/4